version: '3.5'
services:
    mysql:
        build: ./mysql/dockerfile
        container_name: kanatra-database
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: RootPassword
            MYSQL_DATABASE: Kanastra

    frontend:
        build: ./frontend/dockerfile
        container_name: kanastra-frontend
        ports:
            - "8080:8080"
        depends_on:
            - mysql

    backend:
        build: ./backend2/dockerfile
        container_name: kanastra-backend
        ports:
            - "8000:8000"
        environment:
            DB_USER: root
            DB_PASSWORD: RootPassword
            DB_HOST: mysql
            DB_NAME: Kanastra
        depends_on:
            - mysql
            - frontend